### ISSUE TITLE
Activity internal traceability

### ISSUE THREAD

**Issue by rogpers-ericsson** [Ericsson/eiffel#107]
The traceability on the event level is rich and detailed, allowing all sorts of analysis and monitoring.

However, once inside an activity you are entering a new domain of sorts where this kind of traceability is no  longer available. Things that one conceivably want to have traceability on is which services that has been used/called as part of a particular activity execution.

1. Is this a sufficiently big or interesting problem to merit thinking about?
2. Is this something that Eiffel should have a say on?

jet.com has implemented one particular solution to this, as explained in [Focus on the Process, Not on Individual Microservices](https://www.infoq.com/news/2016/12/process-before-microservices).

**Comment by d-stahl-ericsson** [comment]
A sufficiently interesting topic to be sure, but less certain whether this should actually be within Eiffel's scope. I also find Netflix' Conductor to be very interesting in this space (https://netflix.github.io/conductor/)

My thinking is that these are two different domains, though. On the one hand, there is the question of HOW the pipeline operates. I regard the pipeline as any other (cloud) software application. As such, you need to develop, deploy, operate and monitor that application as you would any other. There are excellent tools that do that - from my understanding the solution you linked to belongs in this domain.

On the other hand, there is the common denominator of WHAT these pipelines do, which is to produce software. And keeping track of that software through its life cycle is what Eiffel does.

The boundary between these two isn't always very clear, but I think we should try to stay on in the WHAT domain rather than the HOW domain, because in the latter there are already much more complete solutions than we could hope to offer.

Does that make sense? What are your thoughts?

**Comment by rogpers-ericsson** [comment]
Yes, it makes sense.

I agree that the WHAT and HOW are separate domains. The problems comes when these are connected (in a specific implementation). The connection becomes important in sort of secondary scenarios: trouble shooting, detailed analysis of resource usage per activities etc.

I agree that this is probably not something that Eiffel should involve itself in (formalize), at least not short term.

If needed the activity id could always be passed along in internal calls as some kind of meta data.

**Comment by rogpers-ericsson** [comment]
Closing this with no further action planned.
