### ISSUE TITLE
Add info about included testCases to EiffelTestSuiteStartedEvent?

### ISSUE THREAD

**Issue by e-backmark-ericsson** [Ericsson/eiffel#120]
For monitoring purposes it would be good to know what test cases a test suite consists of.

Similarly it would be good to know how many suites there are in a test activity, to be able to monitor the progress of the test activity.

**Comment by d-stahl-ericsson** [comment]
Can you provide a PR showing how you envision that?

**Comment by e-backmark-ericsson** [comment]
PR created.

Skipping the test suites to test activity mapping for now. It might not be very useful.

**Comment by d-stahl-ericsson** [comment]
Following further offline discussions and input from implementation work, a viable solution to this problem is to restructure the test events somewhat. Rather than adding "precognizant" information to EiffelTestSuiteStartedEvent, the root cause is that the representation of tests is different from that of activities. In activities, we have -Triggered, -Started, -Finished and -Canceled. For tests, there is only -Started and -Finished. This leads to several limitations, including what prompted this issue in the first place: the inability to declare intent.

It could also be argued that TestSuiteStarted and TestSuiteFinished, given those changes, are obsolete and should be replaced by e.g. TestSuiteDefined (the duration of which is by definition up until all Triggered test cases have Finished or been Canceled), but I recommend keeping them the way they are for now, for two reasons:
- Let's be conservative and only make as large changes as we actually have to. We can always revisit later if necessary.
- Finished and Started may serve a purpose anyway. I'm not aware of such a use case currently, but can very easily imagine a situation where a Suite is non-deterministic and doesn't Trigger all test cases upfront. It would be useful for the entity controlling such a suite to be able to explicitly wrap it in a Start and a Finished.

I'll submit a PR according to the above. It's going to be fairly comprehensive, so any help in reviewing it will be valuable.

**Comment by e-backmark-ericsson** [comment]
👍
