### ISSUE TITLE
Handling of environment issues in test case execution

### ISSUE THREAD

**Issue by rogpers-ericsson** [Ericsson/eiffel#123]
In EiffelTestCaseFinishedEvent there are fields for verdict, conclusion and description.

It is not an uncommon situation that test case execution fails due to some random environment error. For scenarios where this is a "common" thing, the need for classification and statics shows up.

How/where to represent that a test case (or test suite possibly) had an error due to an environment fault of some specific type (if that can be determined), in a machine readable format?

**Comment by d-stahl-ericsson** [comment]
Isn't the documentation rather clear on this, or am I missing something?
From https://github.com/Ericsson/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseFinishedEvent.md, if you are unable to execute the test case due to a problem in the environment, use data.outcome.conclusion FAILED.

**Comment by rogpers-ericsson** [comment]
Yes, that is clear. But how to communicate _why_ it failed? 

For the test case execution this is of no relevance, it simply failed. From a continuous improvement perspective this is important information: do we have some recurring types of issues?

**Comment by d-stahl-ericsson** [comment]
Ok, I see. So what we're looking for is some enumeration of reasons for inability to execute a test case? If there's some standard, let's use it. I wouldn't want to try to specify anything like that myself... :)

**Comment by d-stahl-ericsson** [comment]
This has been up for discussion before, by the way. The fundamental problem is that the scope of such an array would essentially be "Everything that could possibly go wrong when executing software in any context", and I don't see how that can be captured in a reasonable way. Either you end up with something so abstract so as to be meaningless, or something way too detailed. Which is why there's the data.outcome.description property, so if you as a user define your own error codes that make sense to you, you can put them there.

**Comment by d-stahl-ericsson** [comment]
Any way forward on this? Close or keep?
