### ISSUE TITLE
Include commit message in EiffelSourceChangeCreatedEvent

### ISSUE THREAD

**Issue by a-broman-ericsson** [Ericsson/eiffel#135]
To be able to trace individual commits with higher level Customer value packs/features it would be good to have  the commit message as part of the EiffelSourceChangeCreatedEvent. SO when you commit you can include information about the context in which the commit was done, for example to contribute to new a customer feature or to correct a trouble report.

**Comment by d-stahl-ericsson** [comment]
Including the commit message isn't a bad idea, but there's always the balance of duplication vs. referencing of information which is, after all, external. The commit messages can easily be retrieved from the SCM system if necessary. But for the sake of convenience, they could be included... but then why not include the actual issues referenced as well. Where to draw the line?

The actual examples you provide are actually catered for already. Rather than including it as unstructured text in the form of commit messages, we try to add value by providing them as structured data in data.issues. What you typically do is you parse the commit message (in your SCM tool of choice, say Gerrit or GitHub Enterprise or BitBucket) and include any references to bugs or features or requirements in data.issues.

**Comment by a-broman-ericsson** [comment]
OK, if we get the information like you say then I am ok. It is of course better to have it as structured data rather than free text.

**Comment by d-stahl-ericsson** [comment]
Ok to close this? Does anyone mind?

**Comment by a-broman-ericsson** [comment]
OK to close! Present definition apparently enables the possibility to trace/determine the content of the commit.
