### ISSUE TITLE
Reference data set & Generator

### ISSUE THREAD

**Issue by erobged** [Ericsson/eiffel#138]
I have a issue regarding the default.md & numbering convention of the events themselves.
For example TCS7 , TCS6 & TCS5 all occur in time before TCS4 , TCS3 & TCS1.
Another example is EDef2 occurs in time before EDef 1.
It appears the correct way to read the links, is from the bottom of the page up to the top. (start at the last event and work backwards).
This creates a bit of conflict with the numbering if the flow of time is taken into consideration.
 (e.g EDef2 occurs before EDef1).
In addition , it make it difficult to scale the link model.

Maybe all that is needed to resolve the conflict is to clarify how to read the link flows with respect to time.

**Comment by erobged** [comment]
@d-stahl-ericsson 
I have a proposal to remedy the time versus the event numerical value issue.
What if we removed the numerical value itself altogether (e.g TCS7 becomes just TCS) and simply state in the diagram that each event in the diagram represents an individual event in time.
This would allow us to scale and would result in little work to resolve the issue in terms of editing etc,,.

**Comment by d-stahl-ericsson** [comment]
There's a point to being able to uniquely identify each event, though, and that point would be lost in that case. But of course you could use something other than an integer, which is indicative of an ordered series, and use a randomized scheme, e.g. "TCS HX" and "TCS SB", but then chances are people would scratch their heads and try to figure out what those acronyms mean...

**Comment by e-backmark-ericsson** [comment]
The event names are also part of the actual reference data set (in the zip file) and there they are specified as customData.name. I assume we have them there merely for documentation purposes? And since json lacks a good way to write comments we added it as customData instead? I see a risk that people will start using customData.name in that way which I assume we didn't intend?

Additionaly - some (a lot of?) _links_ are missing between events in the actual data set.

I propose that we
- renumber the events in the data set to follow the intended order
- update the gliffy accordingly
- break out those names to C-style comments in the json file and then make use of a [JSON Minifier](https://github.com/getify/JSON.minify) to easily remove them before actually using the json file
- add the missing links in between the events in the actual data set

**Comment by erobged** [comment]
sounds like a plan .......
who will do what ?
If you don't mind I could renumber the events and update the gliffy (I need the practice here) ?

**Comment by e-backmark-ericsson** [comment]
Please do! :)

**Comment by d-stahl-ericsson** [comment]
- renumber the events in the data set to follow the intended order

Ok!

- update the gliffy accordingly

Ok!

- break out those names to C-style comments in the json file and then make use of a JSON Minifier to easily remove them before actually using the json file

I have a problem with that. If you run a development project with centralized control of how the data is used, e.g. in a build script or something, that's fine. But that's not what we're doing - we're providing a data set for unknown use cases by unknown users. Then if we say "Oh, it's not really JSON, by the way, it's just sort of like JSON-ish" that's not good. To clarify that adding names in customData isn't encouraged as general practice, we can actually add a disclaimer as a property: "The use of customData properties in this data set is solely for event identification and clarity in the context of usage as a reference data set. It is not encouraged as general practice."

- add the missing links in between the events in the actual data set

Are we talking about event types which are omitted from the data set because they are not mandatory, but would be nice to include, or are we talking about individual links which have been overlooked?

**Comment by erobged** [comment]
I have submitted a Pull request for your review.

**Comment by d-stahl-ericsson** [comment]
This was PR #140, correct? That was closed - any updates on this? Should we keep this issue?

**Comment by d-stahl-ericsson** [comment]
Doing a bit of housekeeping here. I would like to close this issue unless anyone is active working on it. If we want to address this again, we can always create a new issue. Thoughts?
