### ISSUE TITLE
Reconsider not linking data which is needed for triggering.

### ISSUE THREAD

**Issue by a-wensmark-ericsson** [Ericsson/eiffel#70]
Hi!
I’ve been looking through the draft of the Eiffel messaging V4 and there is one thing that bothers me and that is that the triggering information (the GAV) in the _EiffelConfidenceLevelModifiedEvent_ (CLME) and the _EiffelArtifactPublishedEven_ is removed and is instead linked. I think this is very strange. 

To be able to trigger on e.g. a CLME, the trigger first must find out what kind of Artifact the CLME is carrying. This has to be done by a lookup in the ER. So for every CLME the trigger receives, it has to do a lookup in the ER in order to be able to evaluate if it shall trigger on the received event or not. This will put unnecessary load on the ER and also make triggering dependent on the ER, which it is not in Eiffel V3. In my thinking this is a less robust solution.

I would propose the following:
**Data which is vital for triggering should NOT be linked in an event, e.g. GAV or Confidence Level information.**

Baseline information, which I believe is called a “composition” in V4, is on the other hand an example of data which very well can be linked, because even if a composition can refer to one or several Artifacts it is not vital information for a trigger.

**Comment by d-stahl-ericsson** [comment]
Thanks for bringing up this topic! Though pros and cons of this were extensively discussed back and forth internally when we started up the protocol revision work, I don't think it has been addressed and documented publicly.

There are several reasons for the chosen solution.

- One way of looking at it is that by their very nature, Eiffel events are never going to be convenient to analyze in their raw form, anyway. Attempting to make them less inconvenient in certain specific use cases by taking shortcuts is a futile effort.

- Which use cases should be given exceptions, and which should not? Triggering on an event relating to an artifact and wanting to pick out its GAV is a common use case, but far from the only conceivable one. GAVs are easy to uniquely identify with a low risk of ambiguity as to whether two references identify the same entity, or two identical entities. This is far from the case for all entities. Let's assume you want to trigger on events relating to an environment description: you must be able to identify an environment, rather than describing the environment (and thus not knowing if it's the same or an identical one). So if we can't do this well in all cases, we shouldn't do it all.

- Artifacts are not the only valid targets of confidence levels. If we allow an exception in how one references artifacts, but not other entities (for above reasons), should we allow using event links as well? Then you end up with multiple ways of defining a relationship. Or should you enforce using both? That's not appealing either. Whichever way to turn, you end up with poor compromises.

- There's a great deal of truth in the old architectural motto that if your implementation ends up being convoluted, it is probably because your underlying data structure is convoluted. The role of the underlying data structure is not to anticipate certain use cases and make adaptions to makes those convenient. Rather, it is to model the domain in a structured, consistent and unambiguous fashion with conceptual clarity. Instead, it is the role of services and/or derivatives of that underlying data structure to facilitate use cases.

So all in all, if we begin anticipating certain use cases and making compromises for them, we put ourselves on a slippery slope leading to many of the exact problems we revised the protocol in order to get away from.

**Comment by a-wensmark-ericsson** [comment]
Ok, basically what you are trying to say is that “if you have a good architecture, you should stick to it. If you start doing exceptions from it, You’ll end up in a pile of shit!”. This is true, I totally agree!

But, what is a good architecture, or protocol in this case? Is it one that is flawlessly symmetrical or is it one that aids the use and implementation of it?

I have to admit that I did not dare to challenge the ideas behind Eiffel 2.0 at this late stage of the development of the protocol and therefore I suggested an exception, which I knew was a bad idea. But I can conclude that you in your answer did not address my concerns and instead talk about what is good architectural/protocol design. So this time I'll be blunt.

I think the idea of linking data in events is a bad event design and these are my reasons for saying so:

1. A very important part of a good Cx-system is that it is robust. We cannot have a system that has bad uptime capabilities. The best solution to this is to have as less dependencies as possible. In Eiffel “1.0”, you can create Cx-flows that only make use of the MB and the FEM because the events are mostly independent of other events. They contain all the necessary information needed without having to look up anything. In Eiffel 2.0 a dependency to the ER or the “Eiffel intelligence service” has been added, event for the simplest things. Good design is simple not complicated! This is a step away from what was good into something less good.

1. Eiffel “1.0” has been a success, no matter what some people say. But every new solution has things that can be improved and so does Eiffel “1.0”. When you have something that is good you do not throw everything over board and start over from point A again. This will only at the best take us to point B, where we already are, and delay us from arriving at point C. Not to mention the cost this will generate when introducing a non-backward compatible protocol.

1. What is good about Eiffel “1.0” events are that most of them are self-contained. A good event driven system has independent events and the events should have a precise purpose. It is better to have many events than too few and to generic events.

1. I understand that linking data in event makes it simpler to develop the proposed “Eiffel Intelligence service”. By I do not see the reason why this should have precedence over having simple and robust event driven Cx-flows. An “Intelligence service” is possible to do with independent events as well.

1. Another problem with having linked data in events is that there will be race conditions. When an event arrives at a trigger in a FEM it has to do look ups in the ER to get the information it needs in order to know whether the event is of interest to it or not. But what if the linked event has not been processed by the ER yet, then the triggering will fail. This is a very possible scenario since apart from the MB, now also the ER will be a single point of failure in Eiffel 2.0 and most likely a new bottle neck in the system as well. Again, this is another sign of a no-robust design.

1. You can argue that point 5 above can be solved by using the future “Eiffel Intelligence Service” as the trigger instead of the internal MB-triggers in the FEM. The “Eiffel Intelligence Service” aggregates data and can send out a notification when certain conditions are fulfilled. Thus, there will never be any race conditions. But, then again the “Eiffel Intelligence Service” would “solve” a problem that we don´t even have today, and it will do it in a very complicated manner. And on top of that Eiffel 2.0 will have three single point of failure services: the MB, the ER and the “Eiffel Intelligence Service”.

What is your response to this?

**Comment by d-stahl-ericsson** [comment]
Please refrain from discussing internal Ericsson implementations publicly.

**Comment by d-stahl-ericsson** [comment]
Closing.
