### ISSUE TITLE
Introducing EiffelArtifactReusedEvent?

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#82]
I was going through the Build Avoidance usage example, as I was looking to make a screen cast out of it. One thing about it has been bothering me, though, and has always bothered me about the way we handled this scenario in practice.

As the example text states, you have two options. Either you use customData, or you have to make the same decision in multiple places, hoping to reach the same conclusion. The underlying problem is that we have a mechanism for communicating when one DID create a new artifact, but not for communicating when one DID NOT create one.

This has been discussed back and forth before, and we decided not to have such an event, because introducing an event for something that didn't happen is kind of weird. I want to revisit that, however, because such a non-event would be really useful.

So here's my brain dump:
Define EiffelArtifactReusedEvent. Its data object could be completely empty, but it has two important link types: COMPOSITION and ARTIFACT. If you're activity listening for new compositions to build from, and you decide NOT to build from a composition you receive, you emit an EiffelArtifactReusedEvent, pointing at the EiffelArtifactCreatedEvent you're "reusing", and the EiffelCompositionDefinedEvent that you're not building from.

This greatly simplifies the logic of a downstream integrator, who only needs to wait for all components to report in before defining a new composition.

**Comment by guwenqing** [comment]
Hi Daniel

Sorry I haven't fixed Ericsson account yet. I hope it will not matter too much if I use my personal account.

But just want to say that I think it is a good design of the event in the scenario that you are describing in build avoidance section. It helps to solve the complexity when joining the results together.

But when we have:
* Many targeting artifacts could be build: One composition event to start all is not practically possible, for example in Jenkins we cannot create too many jobs representing many artifact builds that are waiting to be started. We have to reuse one or more (smaller number of) common component(s), and in this case many composition events to start many builds is necessary (at least in Jenkins world). In this way, the design of this new event still has value, but looks strange.
* In current design, it is beneficial when the composition event is sent out in a sequential way. In a test avoidance specifically, it is quite common that we have parallel build sessions. It is also possible sometimes in build area.

**Comment by d-stahl-ericsson** [comment]
Using your personal account is fine by me :) When you contribute stuff you should use your Ericsson account, however.

I'm not sure I understand your concern entirely. Is it that in practice, you are in fact working with a large set of compositions, and if one of them changes then you end up triggering N number of activities/Jenkins jobs? If so that is perfectly fine, I don't see that the proposed structure gets in the way of that? For instance, you can aggregate multiple composition into one "super-composition". Or if you prefer to keep them disconnected, trigger your activities based on one or more of those separate compositions.

I don't understand what you refer to by sending the event sequentially? Could you exemplify?

**Comment by guwenqing** [comment]
Sorry for my broken English probably.

We take real examples where we have 90 artifacts in one build if we rebuild all.

If we define 90 Jenkins jobs, we could send out a composition event (one event) to start them all and they decide themselves to see if you want to rebuild or not. Reuse event is very useful here.

But 90 is a bit too much, and this is increasing. So practically we intend to have only one job, and to trigger N artifacts rebuild, we have to send out N different composition event in one build session. So one job is started N times. When we do this way, it is more natural to send N artifacts after applying build avoidance, so the ones do not need to be rebuilt will not need to start at all. Having one job instead of 90 also helps if we add more artifacts, in that case no change is needed.

We can still follow the same/similar idea as you have proposed, but they do not look natrual. In our case, we can make our build avoidance job always send out 90 events, and always start 90 runs for the same job who follows the same logic to do a real build or just reuse something that is available.

What I mean for sequential is something else.
Today practically we are using a controller to coordinate such build. Because we cannot use the recommendation as you have described in build avoidance section in an easy way. We would like to if we can because coordinator is quite complicated and it is blocking and waiting online.

If the session is started sequentially, meaning a new session will not start if the old one is still ongoing, with the use of "Reuse" event, the complexity is solved. 

But if the two sessions are allowed to start at the same time, and they almost arrive the same time, the "joining" component has to know precisely which copy of the sub artifact X is the one you need to wait for. One can claim that the event has enough data to distinguish, for example artifact version or SHA1, but when we support manual build etc, it is complicated. "Batch" number this kind of thing maybe can be added to improve. Just want to say it is still not trivial even if we add "Reuse" event.

**Comment by d-stahl-ericsson** [comment]
Ah, I understand. Thanks for bringing these topics up, these are very important questions!

What you're describing is essentially the choice between a centralized and a decentralized approach. I don't think there's any right or wrong here, depending on the circumstances you might choose one or the other, as long as one does it with open eyes, as you are doing. Or you may go for a hybrid approach: it may be that the 91st component in your case requires particular handling, is done by some third party or for other reasons needs to be decentralized.

The proposed solution is designed to not only cover either case, but to insulate other parties (CDefS in the example) from what you choose. I don't see why you would end up sending a bunch more CompositionDefined because you re-use a single versatile Jenkins job, rather than 90 specialized Jenkins jobs: there's nothing dictating there's a 1:1 mapping between events and job executions. So in one case you trigger 90 jobs once, in another you trigger one job 90 times. The only difference is that in the first case, each job needs one parameter: the source revision (the component to build is intrinsic to the job definition). In the second case the one job needs two parameters: the source revision and the component.

About sequentiality: of course, multiple of these compositions may be going on in parallel. And indeed, some may be left "hanging" and incomplete indefinitely. The implication is that the agent emitting CDefS needs to maintain a state: for every CDefC received, keep track of artifacts created or reused. Essentially, you can use the CDefC itself as your key (how I think you want to use "batch number") in that dictionary.

Naturally, if you do that without any checks whatsoever you can end up with CDefS events in a non-linear order (i.e. a newer system version might end up being built before an older version, and therefore appear to be older). Depending on how sophisticated you want to be you can guarantee sequentiality with more or less complicated logic. A simple approach would be this: whenever you emit a CDefS (i.e. all components are accounted for), drop any entry for CDefC events than for this one: in effect, always give up on older unfinished compositions than the latest you successfully built.

**Comment by guwenqing** [comment]
Thanks for the detail answer.
I fully agree with you there's no essential difference compared to one job triggering 90 times or 90 jobs triggering 1 time. 

However practical speaking, with today's Eiffel + Jenkins + FEM, we cannot trigger one job 90 times by just one event. It can be we are wrong, but we have many discussions internally, we do not think there's a way today.

As I said if we are out of this picture, and look at the things in a more concepture way, it should be OK. And hopefully we could have some practical things that can fulfill this requirement soon.

For the sequential/parallel thing, as you say, technically there's way. So I agree with you, we can solve it with some logics anyhow. Not a big issue.

**Comment by d-stahl-ericsson** [comment]
Please refrain from naming and discussing internal proprietary solutions in this context (I edited your reply).

Yes, the protocol as such doesn't know anything about Jenkins job configurations, but of course operates on a purely conceptual level. But we're engineers and we are of course pragmatists as well :)

To speak in very general terms (as we must), I would offer that the solution lies in being very conscientious about separating triggering logic from activity execution logic. I.e. the thing that reacts to an event and configures an activity (e.g. a Jenkins job) is a separate concern from the thing that performs that activity. One of my beefs with Jenkins is the way it mixes those two concerns up, making solutions to situations like these rather convoluted.

Will be happy to continue the discussion internally :)
